

POST http://localhost:3000/api/create-post-without-kafka HTTP/1.1
Content-Type: application/json

{
    "author": "sounish",
    "title": "Blog title 2",
    "subtitle": "Subtitle 2",
    "content": "My blog content 2"
}


POST http://localhost:3000/api/create-post-with-kafka HTTP/1.1
Content-Type: application/json

{
    "author": "sounish",
    "title": "Blog title 2",
    "subtitle": "Subtitle 2",
    "content": "My blog content 2"
}